name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: build the project
      run: |
        npm i
        npm run build:all
    - name: stop the server
      run: |
        docker-compose down
        docker image prune -a -f
    - name: start the server
      run: docker-compose up -d
